### PR TITLE
Dev chat stream

### PR DESCRIPTION
**Pull request by larynjahor**

### CODE REVIEW

**Comment by larynjahor** [comment]
image

**Comment by slntopp** [comment]
What's `0:` prefix?

**Comment by larynjahor** [comment]
> What's `0:` prefix?

It's sender's ID. In this case it is nocloud root account.

**Comment by slntopp** [comment]
Pls, use titles instead, and short uuids somewhere aside

**Review by slntopp — APPROVED** [review]

**Pull request merged**
